[application]

[web.app]

# HTML title tag content
title = "Yarik Weather"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[mobile.android]
# Android-specific configuration
disable_kotlin = false
# Use a valid Android Gradle Plugin version
agp_version = "8.5.0"
# Android SDK versions
compile_sdk = 34
min_sdk = 24
target_sdk = 34
# Application ID
application_id = "com.yourcompany.frontend"
# Version information
version_code = 1
version_name = "1.0"

[build]
optimize = false