/**
 * Coastal cities database — used to determine if a location
 * has sea temperature data worth displaying and swimming recommendations.
 */

// ── 10 coastal cities of Crimea ──
const CRIMEA_COASTAL = [
  'y alta',
  'sevastopol',
  'feodosia',
  'evpatoria',
  'sudak',
  'alupka',
  'bachchysaray',
  'kerch',
  'alushta',
  'saki',
  'yalta',
  'theodosia',
  'yevpatoriya',
  'yevpatoriya',
  'alushta',
  'foros',
  'koktebel',
  'novy svet',
  'miskhor',
  'gurzuf',
  'partenit',
  'rybachye',
  'morskoye',
  'veseloye',
  'primorsky',
  'beregovoye',
  'peschanoye',
  'nikolayevka',
  'vilino',
  'orskoye',
  'khersones',
  'balaklava',
  'inkerman',
  'kach',
  'orlovka',
  'lyubimovka',
  'peski',
  'uglovoye',
  'zaozernoye',
  'molochnoye',
  'popovka',
  'medvedevo',
  'shtormovoye',
  'mirny',
  'novoozornoye',
  'mezhvodnoye',
  'chernomorskoye',
  'olenevka',
  'mariyno',
  'ordzhonikidze',
].map((c) => c.toLowerCase().trim());

// ── 50+ coastal cities of Rest Russia (excluding Crimea) ──
const RUSSIA_COASTAL = [
  'sochi',
  'adler',
  'dagomys',
  'lazarevskoye',
  'tuapse',
  'gelendzhik',
  'novorossiysk',
  'anapa',
  'taman',
  'yeysk',
  'primorsko-ahtarsk',
  'temryuk',
  'kabardinka',
  'divnomorskoye',
  'arkhipo-osipovka',
  'vladivostok',
  'nakhodka',
  'ussuriysk',
  'artem',
  'bolshoy kamen',
  'partizansk',
  'spassk-dalny',
  'lesozavodsk',
  'dalnegorsk',
  'dalnerechensk',
  'fokino',
  'preobrazheniye',
  'plastun',
  'ternay',
  'olga',
  'kavalerovo',
  'slavyanka',
  'posyet',
  'zaruibino',
  'bangkok',
  // Kaliningrad coast
  'kaliningrad',
  'zelenogradsk',
  'svetlogorsk',
  'pionersky',
  'yantarny',
  'baltiysk',
  'svetly',
  'otradnoye',
  'lesnoye',
  'krylovo',
  // Murmansk coast
  'murmansk',
  'severomorsk',
  'polyarny',
  'kola',
  'teriberka',
  'vidyayevo',
  'snezhnogorsk',
  'zaozersk',
  'gadzhiyevo',
  'polyarnye zori',
  // St Petersburg coast
  'st petersburg',
  'kronstadt',
  'sestroretsk',
  'zelenogorsk',
  'petergof',
  'lomonosov',
  'primorsk',
  'vyborg',
  'sovetsky',
  'vysotsk',
  'kamennogorsk',
  // Archangelsk coast
  'arhangelsk',
  'severodvinsk',
  'novodvinsk',
  'onega',
  'belomorsk',
  'kem',
  'kandalaksha',
  // Azov sea
  'taganrog',
  'azov',
  'yeysk',
  'primorsko-ahtarsk',
  'temryuk',
  // Sakhalin
  'yuzhno-sakhalinsk',
  'korsakov',
  'kholmsk',
  'nevelsk',
  'poronaysk',
  'okha',
  'aleksandrovsk-sakhalinsky',
  'makharov',
  'dolinsk',
  'aniva',
  'tomari',
  'uglegorsk',
  'shakhtyorsk',
  // Kamchatka
  'petropavlovsk-kamchatsky',
  'vilyuchinsk',
  'yelizovo',
  'ust-kamchatsk',
  // Khabarovsk coast
  'sovetskaya gavan',
  'vanino',
  'nikolaevsk-on-amur',
  'okhotsk',
  // Magadan
  'magadan',
  'ola',
  'sussuman',
  // Chukotka
  'pevek',
  'provideniya',
  'egvekinot',
  'anadyr',
  'bilibino',
].map((c) => c.toLowerCase().trim());

// ── 50+ coastal cities outside Russia ──
const WORLD_COASTAL = [
  'miami',
  'barcelona',
  'nice',
  'cannes',
  'monaco',
  'valencia',
  'malaga',
  'lisbon',
  'porto',
  'dubai',
  'abu dhabi',
  'shanghai',
  'sydney',
  'melbourne',
  'rio de janeiro',
  'bangkok',
  'phuket',
  'patong',
  'koh samui',
  'pattaya',
  'sanya',
  'okinawa',
  'honolulu',
  'los angeles',
  'san diego',
  'san francisco',
  'seattle',
  'vancouver',
  'toronto',
  'montreal',
  'new york',
  'miami beach',
  'fort lauderdale',
  'tampa',
  'naples',
  'key west',
  'providence',
  'boston',
  'acapulco',
  'cancun',
  'playa del carmen',
  'puerto vallarta',
  'manila',
  'cebu',
  'bali',
  'jakarta',
  'surabaya',
  'singapore',
  'kuala lumpur',
  'penang',
  'larnaca',
  'limassol',
  'haifa',
  'tel aviv',
  'beirut',
  'casablanca',
  'tangier',
  'marrakesh',
  'alexandria',
  'sharm el sheikh',
  'hurghada',
  'dubrovnik',
  'split',
  'zadar',
  'venice',
  'genoa',
  'naples',
  'palermo',
  'bari',
  'olbia',
  'cagliari',
  'athens',
  'thessaloniki',
  'istanbul',
  'izmir',
  'antalya',
  'marmaris',
  'bodrum',
  'kemer',
  'alanya',
  'sibenik',
  'rovinj',
  'pula',
  'porto cervo',
  'santorini',
  'mykonos',
  'crete',
  'rhodes',
  'corfu',
  'halkidiki',
  'batumi',
  'poti',
  'supsa',
  'constanta',
  'mamaia',
  'varna',
  'burgas',
  'nessebar',
  'sozopol',
  'golden sands',
  'sunny beach',
  'albena',
  'cape town',
  'durban',
  'maputo',
  'mombasa',
  'dar es salaam',
  'zanzibar',
  'goa',
  'mumbai',
  'chennai',
  'kochi',
  'colombo',
  'male',
  'osaka',
  'tokyo',
  'fukuoka',
  'nagasaki',
  'hiroshima',
  'busan',
  'incheon',
  'da nang',
  'nha trang',
  'ho chi minh',
  'ha long',
  'danang',
  'hue',
  'seoul',
  'kaohsiung',
  'hong kong',
  'macau',
  'busan',
  'jeju',
  'taichung',
  'perth',
  'adelaide',
  'brisbane',
  'gold coast',
  'cairns',
  'auckland',
  'wellington',
  'christchurch',
  'hobart',
  'darwin',
  'fiji',
  'suva',
  'nadi',
  'noumea',
  'port vila',
  'apia',
  'honara',
  'port moresby',
  'san juan',
  'havana',
  'varadero',
  'kingston',
  'santo domingo',
  'punta cana',
  'nassau',
  'bermuda',
  'barbados',
  'bridgetown',
  'port of spain',
  'st georges',
  'castries',
  'fort de france',
  'cartagena',
  'santa marta',
  'barranquilla',
  'maracaibo',
  'caracas',
  'paramaribo',
  'cayenne',
  'belém',
  'fortaleza',
  'recife',
  'salvador',
  'rio de janeiro',
  'santos',
  'florianopolis',
  'porto alegre',
  'punta del este',
  'montevideo',
  'buenos aires',
  'mar del plata',
  'ushuaia',
  'valparaiso',
  'vina del mar',
  'santiago',
  'concepcion',
  'callao',
  'lima',
  'guayaquil',
  'manta',
  'salinas',
  'punta arenas',
  'puerto montt',
].map((c) => c.toLowerCase().trim());

const ALL_COASTAL = new Set([
  ...CRIMEA_COASTAL,
  ...RUSSIA_COASTAL,
  ...WORLD_COASTAL,
]);

/**
 * Returns true if the given city name is recognized as a coastal city.
 */
export function isCoastal(city: string): boolean {
  return ALL_COASTAL.has(city.toLowerCase().trim());
}
